//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace WCFTemplate.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - ServiceTemplateContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://services.wcftemplate.jmj/wcf/template/1", Name = "ServiceTemplateContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	[WCF::XmlSerializerFormat]
	public partial interface IServiceTemplateContract 
	{
		[WCF::FaultContract(typeof(WCFTemplate.FaultContracts.TechnicalError))]
		[WCF::FaultContract(typeof(WCFTemplate.FaultContracts.BusinessError))]
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://services.wcftemplate.jmj/wcf/template/1/ServiceTemplateContract/Operation", ProtectionLevel = ProtectionLevel.None)]
		WCFTemplate.MessageContracts.OperationResponse Operation(WCFTemplate.MessageContracts.OperationRequest request);
		
[WCF::FaultContract(typeof(WCFTemplate.FaultContracts.TechnicalError))]
		[WCF::FaultContract(typeof(WCFTemplate.FaultContracts.BusinessError))]
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://services.wcftemplate.jmj/wcf/template/1/ServiceTemplateContract/BusinessMistake", ProtectionLevel = ProtectionLevel.None)]
		void BusinessMistake();
		
[WCF::FaultContract(typeof(WCFTemplate.FaultContracts.TechnicalError))]
		[WCF::FaultContract(typeof(WCFTemplate.FaultContracts.BusinessError))]
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://services.wcftemplate.jmj/wcf/template/1/ServiceTemplateContract/TechnicalMistake", ProtectionLevel = ProtectionLevel.None)]
		void TechnicalMistake();
		
	}
}

