//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace WCFTemplate.MessageContracts
{
	/// <summary>
	/// Service Contract Class - OperationResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "OperationResponse", WrapperNamespace = "http://services.wcftemplate.jmj/wcf/template/1")]
	[WCF::XmlSerializerFormat] 
	public partial class OperationResponse
	{
		private WCFTemplate.DataContracts.OperationOut operationOut;
		
		[WCF::MessageBodyMember(Namespace="http://services.wcftemplate.jmj/wcf/template/1", Order=0)]
		[System.Xml.Serialization.XmlElementAttribute] 
		public WCFTemplate.DataContracts.OperationOut OperationOut
		{
			get { return operationOut; }
			set { operationOut = value; }
		}
		
		public OperationResponse()
		{
		}
		
		public OperationResponse(WCFTemplate.DataContracts.OperationOut operationOut)
		{
			this.operationOut = operationOut;
		}
	}
}