//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace WCFTemplate.MessageContracts
{
	/// <summary>
	/// Service Contract Class - OperationRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "OperationRequest", WrapperNamespace = "http://services.wcftemplate.jmj/wcf/template/1")]
	[WCF::XmlSerializerFormat] 
	public partial class OperationRequest
	{
		private WCFTemplate.DataContracts.OperationIn operationIn;
		
		[WCF::MessageBodyMember(Namespace="http://services.wcftemplate.jmj/wcf/template/1", Order=0)]
		[System.Xml.Serialization.XmlElementAttribute] 
		public WCFTemplate.DataContracts.OperationIn OperationIn
		{
			get { return operationIn; }
			set { operationIn = value; }
		}
		
		public OperationRequest()
		{
		}
		
		public OperationRequest(WCFTemplate.DataContracts.OperationIn operationIn)
		{
			this.operationIn = operationIn;
		}
	}
}